### ISSUE TITLE
Seems it's dissapeared from the Chrome Web Store

### ISSUE THREAD

**Issue by MrDnomaid** [Meadowcottage/GiphyDeck#1]
![image](https://cloud.githubusercontent.com/assets/14424577/16903303/ac110690-4c72-11e6-9d72-946a8b7538a1.png)

**Comment by Meadowcottage** [comment]
This is currently not on the web store because it's still in development :stuck_out_tongue:

**Comment by MrDnomaid** [comment]
Oh, lol. You should probably add that in the readme
